"""Initial PostgreSQL migration

Revision ID: e212a741ce4b
Revises: 
Create Date: 2026-05-13 15:04:40.795943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e212a741ce4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_table('direcciones',
    sa.Column('id_direccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_receptor', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('entradas_blog',
    sa.Column('id_entrada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('favoritos_artistas',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_artista')
    )
    op.create_table('lienzos',
    sa.Column('id_lienzo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lienzo')
    )
    op.create_table('newsletters',
    sa.Column('id_newsletter', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_newsletter')
    )
    op.create_table('obras',
    sa.Column('id_obra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('tecnica', sa.String(length=100), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_obra')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('suscripciones',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_artista')
    )
    op.create_table('bandeja_newsletter',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_newsletter', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_newsletter'], ['newsletters.id_newsletter'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_newsletter')
    )
    op.create_table('comentarios_blog',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrada'], ['entradas_blog.id_entrada'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('favoritos_obras',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.Column('fecha_agregado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id_obra'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_obra')
    )
    op.create_table('historial_stock',
    sa.Column('id_historial', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cambio', sa.Integer(), nullable=False),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('lienzo_items',
    sa.Column('id_lienzo', sa.Integer(), nullable=False),
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_lienzo'], ['lienzos.id_lienzo'], ),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id_obra'], ),
    sa.PrimaryKeyConstraint('id_lienzo', 'id_obra')
    )
    op.create_table('ordenes',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id_direccion'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_table('orden_items',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_orden', 'id_producto')
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('orden_items')
    op.drop_table('ordenes')
    op.drop_table('lienzo_items')
    op.drop_table('historial_stock')
    op.drop_table('favoritos_obras')
    op.drop_table('comentarios_blog')
    op.drop_table('bandeja_newsletter')
    op.drop_table('suscripciones')
    op.drop_table('productos')
    op.drop_table('obras')
    op.drop_table('newsletters')
    op.drop_table('lienzos')
    op.drop_table('favoritos_artistas')
    op.drop_table('entradas_blog')
    op.drop_table('direcciones')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
